# This Notebook is for general practice and exercises related to University of Michigan's Applied Data Science specialization
## This noteboook contains:

#### --NUMPY

# NUMPY

## Array Creation

In [1]:
import numpy as np

In [2]:
# creating a single dimensional array from a list
a = [1,2,3]
array1 = np.array(a)
array1

array([1, 2, 3])

In [3]:
# creating a multiple dimensional array from several lists. The lists must be pased as a single argument (tuple)
b = [1,2,3]
c = [4,5,6]
d = [7,8,9]
array2 = np.array((b,c,d))
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# creating a placeholder array with 0s. The argument is the dimensions (ROW X COLUMN) of the array
array3 = np.zeros((3,3))
array3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# creating a placeholder array with 1s. The argument is the dimensions (ROW X COLUMN) of the array
array4 = np.ones((3,3))
array4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# creating a placeholder array filled with a specific number. The arguments are [ARRAY SHAPE (ROW X COLUMN) TUPLE] [FILLER]
array5 = np.full((5,5),22)
array5

array([[22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22]])

In [8]:
# creating a placeholder array through a range. The arguments are [start number] [end number(exclusive)] [step]. To add dimensionality, use .reshape
array6 = np.arange(1,13,1).reshape(4,3)
array6

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
# creating a boolean array. A boolean array tests every element of on array vs a condition and returns a T/F response.
array7 = array6 > 5
array7

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
# using a boolean array to filter results. 
#A boolean array can be used to "mask" another array and filter results. in the example below, it returns the elements of ARRAY6 where ARRAY7 is TRUE.
array6[array7]

array([ 6,  7,  8,  9, 10, 11, 12])

In [12]:
#basic operations such as sum,substraction and multiplication PER element are supported
array2+array4

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

## Data Retrieval

In [ ]:
#To retrieve 1 ELEMENT from a ONE-DIMENSIONAL ARRAY it is done through slicing just l